name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 15
      matrix:
        operating-system: [ubuntu-20.04, macOS-10.15]
        php-versions: ["8.0", "8.1"]
        symfony-versions: ["5.4", "6.0"]
    name: Test Symfony ${{ matrix.symfony-versions }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pcov
          coverage: pcov

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      - name: Set Symfony version
        run: |
          composer update --prefer-dist --no-interaction
          composer config extra.symfony.require ${{ matrix.symfony-versions }}

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run phpspec
        run: bin/phpspec run -f dot -n

      - name: Run php-cs-fixer
        run: bin/php-cs-fixer fix --verbose --diff --dry-run Mixpanel/
